### ISSUE TITLE
Handlers stop sharing instances by using `shared: false`

### ISSUE THREAD

**Issue by iltar** [hostnet/form-handler-bundle#15]
The handlers are stateful, that's because it contains setters and the data object is integrated inside. There's no real way to prevent this without losing information about types. While the form handlers _are_ services, you never use them like this as they get passed along with the action arguments.

Due to their stateful nature, I'd like to have the collector compiler pass add [the shared option](http://symfony.com/doc/current/service_container/shared.htm) as false to all handlers during container compilation. It might be a slight behavioural change, but I consider this a bug because it gives unexpected results if the handlers are shared.

Would there be any implications when adding this option?

**Comment by yannickl88** [comment]
This is no longer an issue with the new form handlers since it no longer uses the ParameterConverter.

See #21.
