### ISSUE TITLE
Using the `ArgumentValueResolver` instead of `ParameterConverter`

### ISSUE THREAD

**Issue by iltar** [hostnet/form-handler-bundle#16]
Currently we use the [ParameterConverter] to provide the handlers to the action, but this causes 2 side effects:
- Mandatory dependency on the `SensioFrameworkExtraBundle`, depending on bundles is usually not the best idea.
- The arguments are stored in the `Request->attributes`, this means that your request contains services which is not really nice.

I would like to replace the converter by an [ArgumentValueResolver](http://symfony.com/doc/current/controller/argument_value_resolver.html). It would introduce a BC break, so perhaps we can let developers toggle for BC reasons. After updating, a parameter could be set to revert to the old behavior in case the symfony version is not 3.1. This way we could support both variants on demand and automatically until the majority of people starts using ^3.1. 

Perhaps we could still support the parameter converter up until 3.4 is released and remove it afterwards, while making the composer dependency a suggests earlier.

**Comment by yannickl88** [comment]
This is no longer an issue with the new form handlers since it no longer uses the ParameterConverter.

See #21.

**Comment by iltar** [comment]
In theory we can still provide a shortcut for the handler in a similar way via argument value resolvers, eliminating the dependency on the factory directly

**Comment by yannickl88** [comment]
Sorry, mobile buttons trigger a bit easy :p

**Comment by iltar** [comment]
Unable to do this, because the new handlers return a stateful object from the factory based on the handler, not the actual handler.
