### ISSUE TITLE
See if we can use the simple-phpunit script for tests

### ISSUE THREAD

**Issue by iltar** [hostnet/form-handler-bundle#31]
As @xabbuh mentioned in https://github.com/hostnet/form-handler-bundle/pull/30#discussion_r115439800, listeners and such would be automatically registered using the `simple-phpunit` script provided by the `symfony/phpunit-bridge` package that we use. Right now we are depending on this in our dev dependencies `"phpunit/phpunit": "^4.7|^5.0",`. I think it's a viable alternative to check if we can use the bridge for this.

**Comment by xabbuh** [comment]
see #32

**Comment by yannickl88** [comment]
closed, see #32
