### ISSUE TITLE
Adding custom errors to form in onSuccess-case

### ISSUE THREAD

**Issue by daFish** [hostnet/form-handler-bundle#33]
Is it possible to get the current `Form`-instance when I handle the post-processing in `onSuccess`? 

The reason I need the form is that I update a present entity using a DTO (which is defined as the `data_class`-attribute of the form) and trigger the `UniqueEntity`-validator.

**Comment by yannickl88** [comment]
Yes, this is possible. The FormInterface is passed as the second argument in the `onSuccess` and `onFailure` methods. The full signature for the callbacks is:
```
function (object $data, FormInterface $form, Request $request): void
{
}
```

A quick glace through the docs does indeed not tell this. I will create an issue to fix this.

> PS: If you are using the old handlers, you can use `FormHandlerInterface::getForm()`.

**Comment by daFish** [comment]
@yannickl88 Thanks for the hint. Works as expected.
