### ISSUE TITLE
Manual form submit

### ISSUE THREAD

**Issue by latysh** [hostnet/form-handler-bundle#39]
Hi guys,

I have a POST API endpoint. When I send request to this URL using POSTMAN

`$handler->handle($request, $cardData)` function returns null as a result of form not being submitted. Without this bundle I used to manually submit data to the form using this example https://symfony.com/doc/current/form/direct_submit.html. Is there any workout how to manually submit data to the handler?

**Comment by yannickl88** [comment]
interesting use case, this is indeed something we have not yet considered. However, I think we can add an option to the `HandlerConfigInterface` which could give you more freedom on how to process submission.

I'll discuss this with @iltar if we want to support this and will get back to you soon.

**Comment by iltar** [comment]
@latysh do you have an example on how you handle those forms?

**Comment by yannickl88** [comment]
After some discussion we agreed that we can add support for a custom form submit option. I cannot give you an ETA but most likely we will add something in the coming weeks. If you need it sooner, you are welcome to open a PR.

**Comment by iltar** [comment]
@latysh Would this change be sufficient to what you need? hostnet/form-handler-component#21

It would allow you to do this:
```php
public function configure(HandlerConfigInterface $config)
{
    $config->setFormSubmitProcessor(function (FormInterface $form, Request $request) {
        // taken from the Symfony docs example
        $form->submit($request->request->get($form->getName()));
    });
}
```

**Comment by yannickl88** [comment]
@latysh A commit has been merged into the component. Could you verify if the solution @iltar gave works for your case?

**Comment by latysh** [comment]
Hi guys,

Thanks a lot for this. Did not have time to test it out. Will test it tomorrow and let you know. 

Once again, many thanks.
Al

**Comment by yannickl88** [comment]
Cool, thanks! We didn't slap a version on it yet, but you can test it by using `dev-master`.

**Comment by latysh** [comment]
Hi guys,

Did you merge it to master? When I install dev-master it gets d39d7544a2a617791504d9f804f5bbbdbddf623b which is dated to Jun 16 2017.

Cheers,

**Comment by latysh** [comment]
Hi guys,
Thanks a lot for your help. Have tested changes out right now and it worked perfectly. 
Want to help out with documentation of this change if you do not mind. 

Cheers,

**Comment by iltar** [comment]
@latysh awesome! My guess is that we can add a page to the wiki: https://github.com/hostnet/form-handler-bundle/wiki

If you can't add a new one yourself, are you willing to add the markdown for it to this issue? Then we can add it for you. The idea I had for this page is a dedicated page which we can list under https://github.com/hostnet/form-handler-bundle/wiki#documentation

**Comment by yannickl88** [comment]
@latysh a new version has been created which includes the feature. Version [1.5.0](https://github.com/hostnet/form-handler-component/releases/tag/1.5.0) of the hostnet/form-handler-component.

**Comment by iltar** [comment]
The feature has been added. I've opened a new ticket for the documentation request.
