### ISSUE TITLE
Is support for Sensio Framework-extra bundle dependency version 5.0 possible?  

### ISSUE THREAD

**Issue by oscargala** [hostnet/form-handler-bundle#59]
Hi,

I'm in the process of upgrading my application to symfony 3.4   In the symfony standard installation, they use version 5.0.0 of the Sensio Framework Bundle.  
The Form Handler bundle has a dependency of version 3.*

Would it be compatible with version 5.0 or are there changes needed?

Thank you!

**Comment by yannickl88** [comment]
The only dependencies the form-handler-bundle has are:
```json
"require": {
    "php":                            "^5.6|^7.0",
    "hostnet/form-handler-component": "^1.4.0",
    "symfony/expression-language":    "^2.7|^3.0|^4.0",
    "symfony/http-foundation":        "^2.7|^3.0|^4.0"
},
```

The `sensio/framework-extra-bundle` is a development dependency. We are using this bundle in combination with `5.1.6` and it works fine.

**Comment by iltar** [comment]
The `sensio/framework-extra-bundle` is only required for the old (undocumented) uses of the `FormHandlerInterface`. But as Yannick mentioned, it will work with version 5 regardless.

**Comment by oscargala** [comment]
Great!  So could I write a pull request, or would it be possible for you to change it?
The require-dev dependencies aren't touched in production, but on my local dev environment composer is complaining it can't upgrade because form-handler-bundle strictly requires 3.*

**Comment by iltar** [comment]
Could it be that you're using an older version of this bundle? The dependency was made optional in 1.4.0 (in #38).

> on my local dev environment composer is complaining it can't upgrade because form-handler-bundle strictly requires 3.*

With this bundle as dependency, or working _in_ this bundle? Because the dev dependencies will _never_ leak from a vendor.

**Comment by oscargala** [comment]
With this bundle as a dependency,

I get:

php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - hostnet/form-handler-bundle 1.3.0 requires sensio/framework-extra-bundle 3.* -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v
3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28,
 v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - hostnet/form-handler-bundle 1.3.0 requires sensio/framework-extra-bundle 3.* -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v
3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28,
 v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - Installation request for hostnet/form-handler-bundle 1.3.0 -> satisfiable by hostnet/form-handler-bundle[1.3.0].

**Comment by iltar** [comment]
What does your composer.json define for this bundle? I suspect it's locked to something like `1.3.*` or `~1.3.0`.

**Comment by yannickl88** [comment]
Our latest version is `1.6.1`, I recommend running `composer.phar require hostnet/form-handler-bundle ^1.6.1`.

**Comment by oscargala** [comment]
Urgh, you're right. Sorry. I shouldn't be working on this stuff with a jetlag.  Thanks!

**Comment by yannickl88** [comment]
No problem, glad it's working for you!
